### ISSUE TITLE
TF: Contact Page needs to be redone

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#37]

**Comment by mikedesigner** [comment]
Here it is. Standard contact page. Removed the map since Google map doesn't work in China. Most platforms dont have a contact page as they typically dont serve consumers from their offices. They dont expect people to show up at their office...well unless your Facebook and conduct company tours or something. So the contact form is a good thing to stand out. 
![screen shot 2016-11-16 at 19 27 10](https://cloud.githubusercontent.com/assets/12680304/20345637/0efcfcc6-ac33-11e6-9517-c14bfb71d404.png)
